# Generated by Django 6.0.5 on 2026-06-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreport',
            name='recipent',
        ),
    ]
