# Generated by Django 6.0.5 on 2026-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField()),
                ('analysis', models.JSONField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_hnsw_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='myapi_docum_search__642bd2_gin',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
